# Generated by Django 4.1 on 2022-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_embed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='File',
            field=models.FileField(blank=True, upload_to='Files'),
        ),
    ]
