# Generated by Django 4.1 on 2022-08-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_embed', '0002_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Data',
        ),
    ]
